# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: wasm-navigator
version: '0.0.1'
github: "faithanalog/wasm-navigator"
license: MIT
author: "Faith Alderson"
maintainer: "Faith Alderson"
synopsis: A WebAssembly interpreter in haskell
description: wasm-navigator is a WebAssembly (wasm) bytecode interpreter.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - attoparsec
  - bytestring
  - text
  - binary
  - vector
  source-dirs: library
  ghc-options:
  - -funbox-strict-fields

executables:
  wasm-navigator:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - wasm-navigator
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  wasm-navigator-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - wasm-navigator
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  wasm-navigator-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - wasm-navigator
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
